### ISSUE TITLE
Using pquic with chrome or chromium.

### ISSUE THREAD

**Issue by mayankmclaren** [p-quic/pquic#11]
Hi,
I wanted to know if it is possible to use pquic with Chrome or Chromium.

**Comment by mpiraux** [comment]
QUIC transport-wise, PQUIC supports draft-27. Picking a Chrome version that supports this version should be transport-compatible. Unfortunately, PQUIC does not integrate a HTTP/3 implementation. Thus Chrome should be able to handshake with PQUIC, but exchanging HTTP requests is not supported so far.

**Comment by mpiraux** [comment]
I'm closing this as no further assistance seems to be required.
