### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by ishitachaturvedi** [p-quic/pquic#15]
While trying to build pquic, the final make step in pquic. The error is-
 45%] Built target picoquic-core
make[2]: *** No rule to make target 'picoquic/michelfralloc/libmichelfralloc.a', needed by 'picoquic_ct'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:114: CMakeFiles/picoquic_ct.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by qdeconinck** [comment]
This log error is not complete. What commands did you type? Did you follow the instructions at https://github.com/p-quic/pquic#pquic-on-linux ?

**Comment by ishitachaturvedi** [comment]
Yes, I followed the steps, after building the deps I did-
git submodule update --init
   cd ubpf/vm
   make
   cd ../..
   cd picoquic/michelfralloc
   make
   cd ../..
   cmake .
 -->  make
At this step I got the above error

**Comment by qdeconinck** [comment]
Ok, but could you please provide the full compilation log? Otherwise, it is hard to understand why it fails.

**Comment by ishitachaturvedi** [comment]
I am attaching the error logs with this
[log.txt](https://github.com/p-quic/pquic/files/5430534/log.txt)

**Comment by qdeconinck** [comment]
Ok, so the first error seemed to be solved by `make`ing in the picoquic/michelfralloc submodule. The error now
`/usr/bin/ld: cannot find -lprofiler`
seems to indicate that you don't have the `gperftools` dependency. Could you try first installing it and then remaking the project again?
```bash
# On Ubuntu
$ sudo apt install gperftools
# On Fedora
$ sudo dnf install gperftools
```

**Comment by mpiraux** [comment]
Closing this as it seems that no further assistance is required.
