### ISSUE TITLE
Unable to send my own data using PQUIC

### ISSUE THREAD

**Issue by mayankmclaren** [p-quic/pquic#7]
Hi,
I tried sending data using the client-server implementation by changing index.html but I am unable to send any data by doing so. The index.hltm file keeps resetting itself. 
Am I doing something wrong? If yes then please let me know the correct way to do that.

**Comment by mpiraux** [comment]
Hi,
The picoquicdemo server doesn't support serving a particular directory yet. We have added the -G flag for the client to request a random file of a given length, maybe that would fit your purpose.

**Comment by mayankmclaren** [comment]
Thank you for answering.
I have one more doubt though. If I use the flag as "-G 10000" will I get a random file that is exactly 10KB in size or it can be any file that is under 10KB in size?

**Comment by mpiraux** [comment]
You will get a random file that is exactly 10KB in size. Note also that the download time is reported by the client at the end of its log.

**Comment by mayankmclaren** [comment]
Okay, thanks for the information.
